.circleci/config.yml
=> chore: add CI/CD Hello world pipeline

.vscode/settings.json, Makefile, requirements-dev.txt
- Replace flake8 by pylama
- Fix unit test discovery in VSCode
=> chore: replace flake8 by pylama + fix unit test discovery in VSCode

data/nlu.fr.md, domain.en.yml, domain.fr.yml
Translation of present messages in French
- [X ] PR title follows [Commit Convention](https://www.notion.so/godialogue/Commit-Convention-84fd9a4c149e48c998d760f1c9176df0) 
- [X ] All relevant PR sections are populated, irrelevant ones are removed
=> feat(lang): french messages first assessment flow

app.yml
Add configuration for websocket to work
=> fix: websocket

.circleci/config.yml, README.md, action-server/Makefile, action-server/actions/action_set_risk_level.py, action-server/actions/province_age_form.py, action-server/requirements-dev.txt, action-server/setup.cfg, action-server/setup.py, action-server/tests/test_dummy.py, app.yml, core/Dockerfile, core/Makefile, core/endpoints.yml, core/requirements-dev.txt, core/setup.cfg, core/setup.py, docker-compose.yml
Action server: Add support for lint/test/deploy within circleci.
closes #6
=> feat: support action-server within circleci pipeline (#6)

action-server/actions/daily_ci_enroll_form.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
add implementation of the daily checkin enroll flow
Issue [#22](https://github.com/dialoguemd/covidflow/issues/22)
[DIA-123]: https://dialoguemd.atlassian.net/browse/DIA-123
[SOL-456]: https://dialoguemd.atlassian.net/browse/SOL-456
=> feat: add daily checkin enroll flow (#22)

core/Dockerfile, docker-compose.yml
Removing `--debug` flag in core Dockerfile, and added LOG_LEVEL=DEBUG within docker-compose file.
#31
=> fix(core): remove default --debug flag (#31)

core/data/stories.md, core/domain/domain.en.yml, core/domain/domain.fr.yml
Add returning for check-in flow
Issue [#23](https://github.com/dialoguemd/covidflow/issues/23)
[DIA-123]: https://dialoguemd.atlassian.net/browse/DIA-123
[SOL-456]: https://dialoguemd.atlassian.net/browse/SOL-456
=> feat: add returning for check-in flow (#23)

core/config/config.core.yml, core/data/stories.md, core/domain/domain.en.yml, core/domain/domain.fr.yml
Update and clean up flow messages
Issue [#47](https://github.com/dialoguemd/covidflow/issues/47)
=> feat: update and clean up flow messages (#47)

action-server/actions/daily_ci_enroll_form.py, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Update daily CI enroll flow to version 0.6
Issue [#49](https://github.com/dialoguemd/covidflow/issues/49)
=> feat: update daily ci enroll flow (#49)

action-server/actions/action_severe_symptoms_recommendations.py, action-server/actions/action_suspect_mild_symptoms_exposure_final_recommendations.py, action-server/actions/action_suspect_mild_symptoms_exposure_recommendations.py, action-server/actions/action_suspect_moderate_symptoms_final_recommendations.py, action-server/actions/action_suspect_moderate_symptoms_recommendations.py, action-server/actions/action_suspect_no_symptoms_recommendations.py, core/data/stories.md, core/domain/domain.core.yml
Merge utter actions in suspect flow stories
Issue [#67](https://github.com/dialoguemd/covidflow/issues/67)
=> chore: merge utter actions in suspect flow stories (#67)

action-server/actions/answers.py, action-server/actions/question_answering_form.py, core/domain/domain.core.yml, core/scripts/prepare-training-data.sh
Make the Rasa Core server aware of its language using a slot and use it to query the question answering service with the right language.
* #39
=> feat: Q&A service is now passed the correct language (#39)

core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Implement first message and first question of daily check-in flow for the demo
Issue [#72](https://github.com/dialoguemd/covidflow/issues/72)
=> feat: daily check-in demo flow (#72)

core/data/stories.md, core/domain/domain.en.yml, core/domain/domain.fr.yml
=> fix: daily check-in demo formulation

action-server/actions/action_tested_positive_maybe_cured_final_recommendations.py, action-server/actions/action_tested_positive_mild_moderate_symptoms_recommendations.py, action-server/actions/action_tested_positive_no_symptoms_recommendations.py, action-server/actions/action_tested_positive_not_cured_final_recommendations.py, core/data/stories.md, core/domain/domain.core.yml
Issue [#76](https://github.com/dialoguemd/covidflow/issues/76)
=> chore: merge utter actions in tested positive flow stories (#76)

integration-tests/config.ini, integration-tests/interactions/bot/call_911.jinja, integration-tests/interactions/bot/close_contact.jinja, integration-tests/interactions/bot/macros.jinja, integration-tests/interactions/bot/not_infected.jinja, integration-tests/interactions/bot/older_65.jinja, integration-tests/interactions/bot/select_province.jinja, integration-tests/interactions/bot/self_isolate.jinja, integration-tests/interactions/bot/stay_home_moderate.jinja, integration-tests/interactions/bot/symptoms_fever.jinja, integration-tests/interactions/bot/symptoms_mild.jinja, integration-tests/interactions/bot/symptoms_moderate.jinja, integration-tests/interactions/bot/symptoms_severe.jinja, integration-tests/interactions/bot/travel.jinja, integration-tests/interactions/bot/welcome.jinja, integration-tests/interactions/user/affirm.jinja, integration-tests/interactions/user/affirm_contact.jinja, integration-tests/interactions/user/deny.jinja, integration-tests/interactions/user/deny_contact.jinja, integration-tests/interactions/user/greet.jinja, integration-tests/interactions/user/province/qc.jinja, integration-tests/interactions/user/suspect.jinja, integration-tests/scenario_fragments/suspect.yml, integration-tests/scenarios/suspect/close_contact.yml, integration-tests/scenarios/suspect/mild_symptoms.yml, integration-tests/scenarios/suspect/moderate_symptoms.yml, integration-tests/scenarios/suspect/not_infected.yml, integration-tests/scenarios/suspect/severe_symptoms.yml, integration-tests/scenarios/suspect/travel.yml
Initial batch of end-to-end test definitions for self-assessment (closes #83)
* #83
=> chore: add self-assessment happy path integration tests

action-server/actions/action_set_risk_level.py, action-server/tests/test_action_set_risk_level.py, action-server/tests/test_dummy.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Un-merged conditions for elevated-covid-risk and elevated-medical-risk. If both are present, it shows all the informations
Also added some unit tests for the logic of the action
- [ X] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines 
- [ X] All relevant PR sections are populated, irrelevant ones are removed
=> fix(dialogue): package-id risk conditions (#85)

action-server/actions/daily_ci_enroll_form.py, action-server/tests/form_helper.py, action-server/tests/test_assessment_form.py, action-server/tests/test_daily_ci_enroll_form.py
Add unit tests for assessment and daily ci enroll flows
Issue [#88](https://github.com/dialoguemd/covidflow/issues/88)
=> chore: add unit tests for assessment and daily ci enroll flows (#88)

.circleci/config.yml, core/domain/domain.fr.yml, core/poetry.lock, core/pyproject.toml, core/scripts/validate_domain.py
Small tool that ensures that we have the same responses in french and english.
* #105
=> chore: tool for validating domain files (close #105)

action-server/actions/daily_ci_feel_worse_form.py, action-server/actions/form_helper.py, action-server/tests/test_daily_ci_feel_worse_form.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Implement daily check-in feel worse flow v0.1
Issue [#94](https://github.com/dialoguemd/covidflow/issues/94)
=> feat: daily ci feel worse flow v0.1 (#94)

app.yml
Rasa seems to have fixed their CPU utilization in rasa since 1.2.x. It
doesn't requires as much resources as it was.
Lower rasa to 0.5 core per container and default cpu threshold
Lower action-server to 0.25 core per container
Ram stays the same
=> fix(resources): reduce resource consumption

action-server/actions/daily_ci_feel_no_change_form.py, action-server/actions/daily_ci_feel_worse_form.py, action-server/tests/test_daily_ci_feel_no_change_form.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Implement daily check-in feel no change flow v0.1
Issue [#92 ](https://github.com/dialoguemd/covidflow/issues/92)
=> feat: daily ci feel no change flow v0.1 (#92)

README.md, action-server/Makefile, action-server/poetry.lock, action-server/pyproject.toml
Add a dependency to Rasa integration testing so that it can be executed as a local module in the project. This will be necessary for the pipeline.
* #51
=> chore: add dependency to Rasa integration testing (#51)

action-server/Dockerfile, action-server/db/assessment.py, action-server/db/base.py, action-server/db/reminder.py, action-server/db/utils.py, action-server/poetry.lock, action-server/pyproject.toml, core/pyproject.toml, docker-compose.yml
Created initial ORM models and utilities for Reminders and Assessents.
closes #91
=> feat: add ORM models for reminder and assessment (#91)

action-server/actions/daily_ci_feel_better_form.py, action-server/tests/test_daily_ci_feel_better_form.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Implement daily check-in feel better flow (v0.1)
Issue [#93](https://github.com/dialoguemd/covidflow/issues/93)
=> feat: daily ci feel better flow v0.1 (#93)

action-server/actions/action_send_validation_code.py, action-server/actions/lib/phone_number_validation.py, action-server/tests/lib/test_phone_number_validation.py, action-server/tests/test_action_send_validation_code.py, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Add action to send phone number validation code using SMS
```
from actions.lib.phone_number_validation import (
generate_validation_code,
send_validation_code,
)
...
success = await send_validation_code(phone_number, language, first_name, generate_validation_code())
```
* Closes #58
=> feat: send phone number validation code using SMS

action-server/actions/daily_ci_feel_better_form.py, action-server/actions/daily_ci_feel_no_change_form.py, action-server/actions/daily_ci_feel_worse_form.py, action-server/actions/daily_ci_keep_or_cancel_form.py, action-server/tests/test_daily_ci_feel_better_form.py, action-server/tests/test_daily_ci_feel_no_change_form.py, action-server/tests/test_daily_ci_feel_worse_form.py, action-server/tests/test_daily_ci_keep_or_cancel_form.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Implement daily check-in keep or cancel flow v0.1
Issue [#96](https://github.com/dialoguemd/covidflow/issues/96)
=> feat: daily ci keep or cancel flow v0.1 (#96)

.circleci/config.yml
The integration tests point to the wrong endpoint for dev master deployment.
Closes #135
=> fix: integration testing endpoint (#135)

action-server/actions/action_send_daily_checkin_reminder.py, action-server/tests/test_action_send_daily_checkin_reminder.py
reminder.last_reminded_at updated after reminder has been sent.
=> fix: update reminder.last_reminder_at after reminder has been sent

action-server/actions/action_tested_positive_not_cured_final_recommendations.py, action-server/actions/action_visit_package.py, action-server/actions/assessment_common.py, action-server/actions/assessment_form.py, action-server/actions/tested_positive_form.py, action-server/tests/test_action_visit_package.py, action-server/tests/test_assessment_common.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml, integration-tests-en/interactions/bot/symptoms_mild.jinja, integration-tests-fr/interactions/bot/not_infected.jinja
Had to add an action to calculate the id and play the package message to avoid having ca-None in the id.
Fixed other messages according to comments
closes #141 
closes #142 
closes #143
closes #144 
closes #145 
closes #146
=> fix(flow): default package id and minor errors (#142)

action-server/actions/action_daily_ci_recommendations.py, action-server/actions/action_goodbye.py, action-server/actions/constants.py, action-server/actions/daily_ci_keep_or_cancel_form.py, action-server/actions/home_assistance_form.py, action-server/setup.cfg, action-server/tests/action_helper.py, action-server/tests/test_action_daily_ci_recommendations.py, action-server/tests/test_action_goodbye.py, action-server/tests/test_daily_ci_keep_or_cancel_form.py, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml, core/setup.cfg
Implement daily check-in recommendations flow v0.2
Issue [#97](https://github.com/dialoguemd/covidflow/issues/97)
=> feat: daily ci recommendations flow v0.2 (#97)

action-server/actions/action_daily_ci_early_opt_out.py, action-server/tests/test_action_daily_ci_early_opt_out.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Implement daily check-in early opt out flow v0.2
Issue [#129](https://github.com/dialoguemd/covidflow/issues/129)
=> feat: daily ci early opt out flow v0.2 (#129)

.circleci/config.yml
Will allow usage of test_system job per component
=> chore: bump helm-app orb to latest

core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml, integration-tests-en/interactions/bot/daily_ci_enroll/registration_complete.jinja, integration-tests-en/interactions/bot/stay_home_moderate.jinja, integration-tests-en/interactions/bot/welcome.jinja, integration-tests-en/interactions/user/get_assessment.jinja, integration-tests-en/interactions/user/suspect.jinja, integration-tests-en/scenario_fragments/suspect.yml, integration-tests-fr/interactions/bot/symptoms_moderate.jinja, integration-tests-fr/interactions/bot/welcome.jinja, integration-tests-fr/interactions/user/get_assessment.jinja, integration-tests-fr/interactions/user/suspect.jinja, integration-tests-fr/scenario_fragments/suspect.yml
Fix various flow messages
#153 #154 #156 #157 #158
=> fix: fix various flow messages (#153, #154, #156, #157, #158)

action-server/actions/action_send_daily_checkin_reminder.py, action-server/actions/daily_ci_enroll_form.py, action-server/actions/daily_ci_feel_better_form.py, action-server/actions/daily_ci_feel_no_change_form.py, action-server/actions/daily_ci_feel_worse_form.py, action-server/actions/lib/assessment_persistence.py, action-server/actions/lib/environment.py, action-server/actions/lib/hashids_util.py, action-server/db/assessment.py, action-server/db/reminder.py, action-server/tests/db/test_assessment.py, action-server/tests/lib/test_assessment_persistence.py, action-server/tests/test_daily_ci_enroll_form.py, action-server/tests/test_daily_ci_feel_better_form.py, action-server/tests/test_daily_ci_feel_no_change_form.py, action-server/tests/test_daily_ci_feel_worse_form.py
Save assessment results
closes #62
=> feat: daily assessment persistence (#62)

.circleci/config.yml, action-server/Dockerfile, action-server/db/reminder.py, action-server/jobs/send_reminders.py, action-server/mypy.ini, action-server/poetry.lock, action-server/pyproject.toml, action-server/setup.cfg, action-server/tests/jobs/test_send_reminder.py, docker-compose.yml, job.yml
Add k8s cronjob running every 15 minutes to send due daily reminders. 
closes #61
=> feat: add daily reminder cronjob (#61)

action-server/actions/action_returning_symptoms_not_worsened_recommendations.py, action-server/actions/checkin_return_form.py, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Update return flow to v1.1 (change self-isolate logic)
#140
=> feat: update return flow to v1.1 (#140)

core/domain/domain.en.yml, core/domain/domain.fr.yml
Fix messages in daily ci flow
#172 #173
=> fix: fix daily ci messages (#172, #173)

core/config/config.core.yml
Add seed to ML policy configuration
#139
=> chore: add seed to ML policy configuration (#139)

action-server/covidflow/actions/assessment_form.py, action-server/covidflow/actions/checkin_return_form.py, action-server/covidflow/actions/tested_positive_form.py, action-server/tests/actions/test_assessment_form.py, action-server/tests/actions/test_checkin_return_form.py, action-server/tests/actions/test_tested_positive_form.py
Add unit tests for assessment flows
#199
=> chore: add unit tests for assessment flows (#199)

action-server/covidflow/actions/assessment_common.py, action-server/covidflow/actions/assessment_form.py, action-server/tests/actions/test_assessment_common.py, action-server/tests/actions/test_assessment_form.py, action-server/tests/actions/test_checkin_return_form.py, action-server/tests/actions/test_tested_positive_form.py
This follows a modification to flows that is in v1.2. Added conditions on fever where there were conditions on cough, since they are treated equally as mild symptoms with this modification
closes #167
=> fix(flow): symptoms none with fever (#167)

action-server/covidflow/jobs/send_reminders.py, action-server/covidflow/setup_structlog.py, app.yml
=> chore: temporarily set logs in DEBUG for all environment (+minor fixes)

action-server/covidflow/actions/daily_ci_enroll_form.py, action-server/poetry.lock, action-server/pyproject.toml, action-server/tests/actions/form_helper.py, action-server/tests/actions/test_daily_ci_enroll_form.py, core/data/nlu.en.md, core/data/nlu.fr.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml
Added the validate code flow
closes #196
=> feat(flow): add validation code validation 1.2 (#196)

action-server/alembic/versions/00002_test_profiles.py, docker-compose.yml
Add test profiles DB migration script
#211
=> feat: add test profiles db migration script (#211)

core/domain/domain.en.yml, core/domain/domain.fr.yml, integration-tests-en/interactions/bot/home_assistance/no_help.jinja, integration-tests-en/interactions/bot/welcome.jinja, integration-tests-fr/interactions/bot/welcome.jinja
Add virtual in greeting message and fix 211 link in 211 messages
#205, #212, #230
=> fix: greeting and 211 messages (#205, #212, #230)

app.yml
=> chore: reverted log level

action-server/tests/actions/test_action_send_daily_checkin_reminder.py, app.yml, docker-compose.yml
update daily check-in reminder URL (`/rasa/ci` -> `/chat/ci`)
closes #235 
relates to https://github.com/dialoguemd/covid-19/pull/726
=> chore: update daily check-in reminder URL (#235)

.circleci/config.yml, action-server/covidflow/setup_structlog.py, app.yml, core/Dockerfile, core/channels/__init__.py, core/channels/setup_structlog.py, core/credentials.yml, core/mypy.ini, core/poetry.lock, core/pyproject.toml, docker-compose.yml
The purpose of this PR is to:
- change formating of rasa core from plain text to JSON.
- add a `sender_id` attribute to every relevent log events, allowing us to better trace distinct conversations.
closes #244
=> feat: format rasa core log format (#244)

action-server/covidflow/actions/daily_ci_keep_or_cancel_form.py, action-server/covidflow/actions/home_assistance_form.py, action-server/tests/actions/form_helper.py, action-server/tests/actions/test_daily_ci_keep_or_cancel_form.py, action-server/tests/actions/test_home_assistance_form.py, core/domain/domain.en.yml, core/domain/domain.fr.yml, integration-tests-en/interactions/bot/home_assistance/no_help.jinja
Changed dialogue link in daily ci recommendations to appropriate province link depending on language (some provinces don't have a french version though)
Changed 211 links when province is quebec
Added link to canada.ca for general population as mentioned in #231
closes #231 
closes #252 
closes #256
=> feat(flow): links per province

.circleci/config.yml
Removed the test_integration job to instead use test_system to fix potential port problems.
* Closes #168
=> ci: change integration tests job to test system (#168)

action-server/covidflow/setup_structlog.py, action-server/mypy.ini, action-server/poetry.lock, action-server/pyproject.toml, core/channels/setup_structlog.py, core/mypy.ini, core/poetry.lock, core/pyproject.toml
Fixed sanic logging by adding missing handlers to the loggers. This is caused by a log_file not being passed in rasa.common.utils which might require further investigation.
* Closes #269
=> fix: sanic logging formatting (#269)

.env.example, action-server/covidflow/utils/maps.py, action-server/tests/utils/test_maps.py
```
get_map_url((45.547196, -73.567944))
```
closes #276
=> feat: add google maps facility (#276)

app.secrets.dev.ca2.yaml, app.secrets.prod.ca.yaml
Allow sending events to segment source
=> fix: add segment write key

.circleci/config.yml, core/Dockerfile, core/core/segment.py, core/endpoints.yml, core/mypy.ini, core/poetry.lock, core/pyproject.toml, docker-compose.yml
Added segment source event broker, inspired by https://github.com/dialoguemd/beautiful-mind/blob/master/rasa-stack/rasa_stack/segment.py
To simplify development in local, and contrary to beautiful-mind, core startup will not fail if `SEGMENT_WRITE_KEY` environement variable is not set, but segment source event broker will be disabled.
closes #206
=> Chore segment tracking service

action-server/covidflow/actions/question_answering_form.py, action-server/tests/actions/test_question_answering_form.py, core/core/segment.py, core/domain/domain.en.yml, core/domain/domain.fr.yml, core/scripts/validate_domain.py, covidflow.code-workspace
Add Q&A sample questions to the flow.
* closes #272
=> feat: add Q&A sample questions

.env.example, README.md, action-server/Makefile, core/Makefile
Rendered result: https://github.com/dialoguemd/covidflow/blob/chore-update-readme/README.md
closes #243
=> chore: update README.md (#243)

.circleci/config.yml, app.yml, job.yml
=> chore: migrte to helm v3

action-server/covidflow/actions/action_fallback.py, core/config/config.core.yml, core/domain/domain.core.yml
Add fallback policy and fallback action
closes #296
=> Feat fallback policy

action-server/covidflow/actions/test_navigation_form.py
Add exception logging for errors catched by dialogue while querying clinia or geocoding
=> fix: add logs for error in test navigation

.circleci/config.yml, action-server/covidflow/actions/action_unsupported_intent.py, core/Dockerfile, core/policies/unsupported_intent_policy.py, docker-compose.yml
Add unsupported intent policy
closes #298
=> feat: add unsupported intent policy (#298)

action-server/covidflow/setup_structlog.py, core/channels/__init__.py, core/channels/setup_structlog.py, core/poetry.lock, core/pyproject.toml, load-tests/load_tests/runner.py, load-tests/load_tests/socketio_locustfile.py
Changed channels to properly bind and clear context logging variables.
In addition, hid some socketio debug from rasa since it isn't properly bound.
* Closes #271
=> fix: incorrect sender id in logs (#271)

action-server/covidflow/actions/test_navigation_form.py, action-server/covidflow/utils/testing_locations.py, action-server/tests/actions/test_test_navigation_form.py, action-server/tests/utils/test_testing_locations.py, core/domain/domain.en.yml, core/domain/domain.fr.yml
=> feat: add opening hours to test navigation (#310)

app.secrets.dev.ca2.yaml, app.secrets.prod.ca.yaml
=> chore: add clinia api key

action-server/covidflow/actions/action_greeting_messages.py, action-server/covidflow/actions/question_answering_form.py, action-server/tests/actions/test_question_answering_form.py, core/config/config.core.yml, core/data/nlu.en.md, core/data/nlu.fr.md, core/data/stories.md, core/domain/domain.core.yml, core/domain/domain.en.yml, core/domain/domain.fr.yml, core/policies/unsupported_intent_policy.py, integration-tests-en/interactions/bot/not_infected.jinja, integration-tests-en/interactions/bot/welcome.jinja, integration-tests-en/scenarios/daily_ci/invalid_url/assesssment_enroll.yml, integration-tests-fr/interactions/bot/not_infected.jinja, integration-tests-fr/interactions/bot/symptoms_severe.jinja, integration-tests-fr/interactions/bot/welcome.jinja
Integrate NLU support in the self-assessment entry flow, which will invoke the QA fallback
Changed the content of 3 messages to update
closes #295
closes #328
=> feat: integrate QA fallback (#295)

core/domain/domain.core.yml
Removed rasa session time-out
closes #329
=> fix: remove rasa session time-out (#329)

action-server/covidflow/actions/action_initialize_daily_checkin.py, action-server/covidflow/actions/daily_ci_feel_better_form.py, action-server/tests/actions/test_action_initialize_daily_checkin.py
=> fix: initializing daily-ci only with supported symptoms value

.circleci/config.yml
This will free up resources as soon as they are not needed anymore
=> chore: delete ephemeral release on merge to master

core/data/nlu.en.md, core/data/nlu.fr.md, core/domain/domain.core.yml
Update to Yves version with all needed and not yet needed intents
=> feat(nlu): update NLU data

app.yml
To remove that system from Dialogue critical business infrastructure
=> chore: move to ops node pool

.circleci/config.yml
=> fix: increase deploy timeout in prod

action-server/poetry.lock, app.yml, core/config/config.en.yml, core/poetry.lock
https://github.com/RasaHQ/rasa/issues/6806
=> fix: convert model url

.circleci/config.yml
=> fix: install git in rasa docker image
