dialoguemd/covidflow

- .gitignore
Changed .gitignore to ignore generated files more specifically (instead of globally by file name).
Merge #3 after this one.
[DIA-123]: https://dialoguemd.atlassian.net/browse/DIA-123
[SOL-456]: https://dialoguemd.atlassian.net/browse/SOL-456
> fix: .gitignore to ignore generated files specifically

- action-server/actions/action_cheer_up.py
- action-server/actions/action_set_risk_level.py
- action-server/actions/province_age_form.py
- action-server/tests/test_action_cheer_up.py
- core/Makefile
- core/data/stories.md
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
Asks for province and age after severe symptoms, proposes info package instead of redirection websites
- [X ] PR title follows [Commit Convention](https://www.notion.so/godialogue/Commit-Convention-84fd9a4c149e48c998d760f1c9176df0) 
- [X ] All relevant PR sections are populated, irrelevant ones are removed
> feat: propose info package in assessment (#11)

- action-server/actions/answers.py
- action-server/actions/assessment_form.py
- action-server/actions/question_answering_form.py
- core/data/stories.md
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
Added "self_asssess_done" slot so that ML could distinguish assessment has been done before whatever the number of loops inside QAs.
Added surface support for "need_assessment" and "out_of_distribution" answers from QA service to add these paths to dialogue
Assessment after QA does not change, so the stories are not "complete", we trust that the good intent triggered is enough to start the assessment with memoization. Stories had to be added for QA after assessment and for QA after QA because a prompt disappears when we loop. 
#46 
- [ X] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines 
- [ X] All relevant PR sections are populated, irrelevant ones are removed
> feat(dialogue): allow assessment after QA (#46)

- core/data/stories.md
- core/domain/domain.core.yml
Frontend will very soon send metadata (with timezone) as part of the /greet (initial payload).
The timezone will be used to avoid sending notification in the middle of the night :)
#63
> feat: support metadata entity used in greet intent (#63)

- action-server/actions/action_offer_daily_checkin.py
- action-server/actions/action_suspect_mild_symptoms_exposure_recommendations.py
- action-server/actions/action_suspect_moderate_symptoms_recommendations.py
- action-server/actions/action_suspect_no_symptoms_recommendations.py
- action-server/actions/assessment_form.py
- action-server/actions/home_assistance_form.py
- action-server/actions/self_isolation_form.py
- core/data/stories.md
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
These changes were made to the "suspect"/generic assessment flow:
- added want_assessment option in menu which leads to same flow as suspect (english-only)
- switched fever and province-age questions (this change affects tested-positive and returning flows but they are still logic so I'll wait adjustments in the design to adapt it if necessary)
- added messages explaining check-in and wrapped in an action
- replaced self-isolation and home assistance messages in recommendations by two little forms)
- added one message to recommendations for people with no risk factors
- [ X] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines 
- [ X] All relevant PR sections are populated, irrelevant ones are removed
> feat(dialogue): update generic assessment to v8

- action-server/actions/action_send_daily_checkin_reminder.py
- action-server/actions/lib/exceptions.py
- action-server/db/reminder.py
- action-server/mypy.ini
- action-server/poetry.lock
- action-server/pyproject.toml
- action-server/tests/test_action_send_daily_checkin_reminder.py
- app.yml
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
- docker-compose.yml
Added external event which will be triggerd by the cron job to send daily check-in SMS.
closes #60
> feat: send reminder SMS upon reception of an external event (#60)

- action-server/actions/action_explain_preconditions.py
- action-server/actions/daily_ci_enroll_form.py
- action-server/tests/test_daily_ci_enroll_form.py
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
- integration-tests-en/interactions/bot/daily_ci_enroll/ask_preconditions.jinja
Rename pre_existing_conditions slot to preconditions to match the spec
Issue [#133](https://github.com/dialoguemd/covidflow/issues/133)
> fix: rename pre_existing_conditions slot to preconditions (#133)

- action-server/actions/action_qa_goodbye.py
- action-server/actions/daily_ci_enroll_form.py
- action-server/actions/daily_ci_feel_better_form.py
- action-server/actions/daily_ci_feel_no_change_form.py
- action-server/actions/daily_ci_feel_worse_form.py
- action-server/tests/test_daily_ci_enroll_form.py
- action-server/tests/test_daily_ci_feel_better_form.py
- action-server/tests/test_daily_ci_feel_no_change_form.py
- action-server/tests/test_daily_ci_feel_worse_form.py
- core/data/stories.md
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
Used the same mechanism as before. To do this, added self_assess_done slot to the daily check-in assessments and added stories
I also corrected a tiny unrelated bug in the daily ci enroll flow.
closes #95
> feat(flow): adapt and integrate QA to Daily ci (#95)

- job.yml
oversight while fixing conflict in PR #155
> fix: wrong cron job name

- action-server/actions/action_initialize_daily_checkin.py
- action-server/actions/constants.py
- action-server/actions/daily_ci_assessment_common.py
- action-server/actions/daily_ci_feel_better_form.py
- action-server/actions/daily_ci_feel_no_change_form.py
- action-server/actions/daily_ci_feel_worse_form.py
- action-server/db/assessment.py
- action-server/db/reminder.py
- action-server/tests/test_action_initialize_daily_checkin.py
- action-server/tests/test_daily_ci_feel_better_form.py
- action-server/tests/test_daily_ci_feel_no_change_form.py
- action-server/tests/test_daily_ci_feel_worse_form.py
- core/data/stories.md
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
Saves useful reminder and assessment attributes in slots at the beginning of daily check-in.
After assessment, saves empty attributes with preceding day's values.
closes #59
> feat: fetch user infos on daily ci start (#59)

- action-server/db/reminder.py
- action-server/tests/db/test_reminder.py
> fix: Reminder.create_from_slot_values not working when metadata=None

- core/data/stories.md
Some stories didn't have the `action_initialize_daily_checkin` due to rebase, which created an alternating result depending on the training. either initializing or not.
None. I was too fast to fix ;)
> fix: missing daily ci initialization in stories

- action-server/covidflow/actions/action_send_daily_checkin_reminder.py
- action-server/tests/actions/test_action_send_daily_checkin_reminder.py
Changed the action_send_checkin_reminder to ignore 555 numbers
closes #222
> chore: do not send reminder for test profiles (#222)

- app.yml
This will fix Safari CORS problem with cookie because covidflow is
hosted on dialoguecorp.com and chloe on dialogue.co.
https://github.com/dialoguemd/covidflow/pull/226#issue-417975901
> fix: add dialogue.co domain 

- action-server/alembic/versions/00003_fix_test_profiles.py
Fixed test profiles to remove `ca-` from provinces
Migration result:
```
chloe=# select * from reminder ;
id |          created_at           | last_reminded_at |    timezone     | is_canceled |                                                                                          attributes                                                                                           
----+-------------------------------+------------------+-----------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | 2020-05-14 18:36:43.094815+00 |                  | America/Toronto | f           | {"language": "en", "province": "on", …
```
> fix: test profiles province (#236)

- action-server/covidflow/actions/daily_ci_enroll_form.py
- action-server/tests/actions/test_daily_ci_enroll_form.py
- core/domain/domain.core.yml
Added yet another slot to track if we just sent the validation code to prevent sending error message in any situation where we just had the user entering a bad code
closes #227
> fix(flow): ask code message for resend (#227)

- action-server/covidflow/actions/action_goodbye.py
- action-server/covidflow/actions/action_qa_goodbye.py
- action-server/covidflow/actions/action_severe_symptoms_recommendations.py
- action-server/covidflow/actions/constants.py
- action-server/tests/actions/action_helper.py
- action-server/tests/actions/test_action_qa_goodbye.py
- action-server/tests/actions/test_action_severe_symptoms_recommendations.py
- core/data/stories.md
- integration-tests-en/config.ini
Send custom json payload to bot. Appears to the bot as {endOfConversation: true} to the bot code.
Had to ignore "custom" field in integration tests because the "true" in the actual output is converted to the True atom, but not in the expected output. 
closes #225 
Relates to #159 and #179
> feat: send end_of_conversation message (#225)

- action-server/covidflow/actions/answers.py
- action-server/tests/actions/test_answers.py
Scrub HTML tags out of the markdown provided by the QA.
I did some experiments to ensure that the markdown used by the frontend doesn't allow inline HTML tags as this would be a pointless change.
Closes #13
> chore: format qa answers (#13)

- action-server/covidflow/actions/daily_ci_enroll_form.py
- action-server/tests/actions/test_daily_ci_enroll_form.py
Super-simple validation just got a little less simple. A phone number with length of 11 has to start with a 1 (Canada and US country code)
closes #241
> fix(flow): 11-length phone numbers to start with 1 (#241)

- action-server/covidflow/actions/assessment_form.py
- action-server/tests/actions/test_assessment_form.py
> fix: missing message in fever only flow (#210)

- action-server/covidflow/actions/question_answering_form.py
- action-server/tests/actions/action_helper.py
- action-server/tests/actions/form_helper.py
- action-server/tests/actions/test_question_answering_form.py
- core/data/stories.md
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
Added disclaimer message and corrected appearance of intro message since both would appear at the same time and adding the second message in stories would just have broken things more. Both messages are now in the form, played only for the first question of the conversation.
closes #247, closes #202, closes #239
> fix(flow): question answering intro messages

- action-server/covidflow/actions/question_answering_form.py
- action-server/tests/actions/test_question_answering_form.py
- core/data/stories.md
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
Out_of_distribution status now leads outside the form and to ask what to do next instead of re-asking for the question. 
I had to redistribute the stories with questions after assessments to make sure there was no apparent link between the actions after the form and the symptoms slot to have better prediction scores (had some as low as 0.41, even though the question was the good one, before that. It got up to always better than 0.7, in the cases I could try).
This methid remains fragile and is obviously not ideal.
closes #280
> fix(flow): out of distribution loop (#280)

- action-server/covidflow/actions/constants.py
- action-server/covidflow/actions/test_navigation_form.py
- action-server/covidflow/utils/geocoding.py
- action-server/covidflow/utils/maps.py
- action-server/covidflow/utils/testing_locations.py
- action-server/mypy.ini
- action-server/tests/actions/action_helper.py
- action-server/tests/actions/form_helper.py
- action-server/tests/actions/test_daily_ci_enroll_form.py
- action-server/tests/actions/test_test_navigation_form.py
- action-server/tests/utils/test_geocoding.py
- action-server/tests/utils/test_phone_number_validation.py
- action-server/tests/utils/test_testing_locations.py
- core/data/stories.md
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
- core/scripts/validate_domain.py
- docker-compose.yml
Flow to get test locations and what comes after, carousel included. An error should happen if there is no geocode for a location, but the lack of a phone number just removes the button
Left out:
- link with extension on call button
- propose to try again with another postal code when the the first time was a success (retry inside the form when it doesn't work is implemented)
- geolocalisation
- more information button
closes #282
> feat(flow): get test locations flow (#282)

- action-server/covidflow/actions/test_navigation_form.py
- action-server/covidflow/utils/testing_locations.py
- action-server/tests/actions/test_test_navigation_form.py
- action-server/tests/utils/test_testing_locations.py
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
- core/scripts/validate_domain.py
Generates a description to include in the carousel card based on referral required, appointment required, and clientele. It doesn't follow exactly the design, but close enough. More clienteles were added so the age-related clientele messages are automated to support any age that could be sent.
Added a message for healthcare workers too.
closes #311
> feat(flow): generate testing location description (#311)

- core/data/stories.md
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
- integration-tests-en/interactions/bot/checkin_return/ask_anything_else.jinja
- integration-tests-en/interactions/bot/daily_ci/feel_worse/diff_breathing_worsened.jinja
- integration-tests-en/interactions/bot/daily_ci/general_recommendations_has_211.jinja
- integration-tests-en/interactions/bot/daily_ci/vulnerable_population_recommendations_has_211.jinja
- integration-tests-en/interactions/bot/daily_ci_enroll/registration_complete.jinja
- integration-tests-en/interactions/bot/stay_home_moderate.jinja
- integration-tests-en/interactions/bot/welcome.jinja
- integration-tests-fr/interactions/bot/welcome.jinja
Added test navigation option when necessary (needed to split one message because we offer test navigation after assessment only if the person has symptoms), including in entry message
closes #273 
Do not merge until #310 is done
> feat(flow): integrate test navigation to dialogue (#273)

- action-server/covidflow/actions/test_navigation_form.py
- action-server/covidflow/utils/geocoding.py
- action-server/covidflow/utils/maps.py
- action-server/covidflow/utils/testing_locations.py
- action-server/mypy.ini
- action-server/poetry.lock
- action-server/pyproject.toml
- action-server/tests/actions/test_test_navigation_form.py
- action-server/tests/utils/test_geocoding.py
- action-server/tests/utils/test_maps.py
- action-server/tests/utils/test_testing_locations.py
There's no way to display the address in the static map and it was decided not to write it in the description, but if we have the address, then it is used for the directions link.
Straight distance is displayed for complexity reasons and lack of an appropriate API key. Since the means of transportation can change, an approximation is as good as a travel distance could be. Distance is displayed in the description since it would steal some space of the clinic name that is only on one line.
closes #325
> feat: use address and display distance (#325)

- core/config/config.en.yml
- core/config/config.fr.yml
In order to avoid this:
tokenizer set to `case_sensitive = false`
> fix: making tokenizer case insensitive

- action-server/tests/utils/fake_server.py
- action-server/tests/utils/test_phone_number_validation.py
Fix an issue related to running async tests under python version 3.6.8. Currently these tests were either not actually running or were skipped.
* Closes #334
> fix: skipped async tests (#334)

- action-server/covidflow/actions/test_navigation_form.py
- action-server/tests/actions/test_test_navigation_form.py
Clear all slots (except featurized test_navigation_success slot) at submit. Clearing them at the beginning of the form (in `form._activate_if_required`, that we use to display intro messages) doesn't work if done cleanly because validation of already present slots takes place before slot values can be erased, and there is a lot of logic and messages in the validation.
closes #341
> feat(flow): make test navigation re-doable (#341)

- action-server/covidflow/actions/action_goodbye.py
- action-server/covidflow/actions/action_qa_goodbye.py
- action-server/tests/actions/test_action_goodbye.py
- action-server/tests/actions/test_action_qa_goodbye.py
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
- core/scripts/validate_domain.py
- integration-tests-fr/config.ini
Added the field to all messages with buttons
Validate in domain validation that text field is disabled for the same messages
closes #344
needs https://github.com/dialoguemd/covid-19/issues/756
> chore(messages): adjust to allow toggling text field (#344)

- action-server/covidflow/actions/question_answering_form.py
- action-server/tests/actions/test_question_answering_form.py
- core/data/stories.md
- integration-tests-en/interactions/user/q_and_a/submit_question.jinja
- integration-tests-en/scenarios/q_and_a/entry_success_no_feedback.yml
If we ask for feedback and receive something else, we artificially bring the dialogue to the point it would be if feedback was given and we had asked if the user had another question, replaying the user input to the dialogue.
This part of the logic could have been simpler and cleaner in the stories, but getting the feedback slot out of the form would have brought its lot of complications, so all in all this was the simplest way
closes #343
https://github.com/dialoguemd/covidflow/pull/346 has to be merged before
> Feat make feedback non mandatory (#343)

- core/core/policies/unsupported_intent_policy.py
- core/data/stories.md
- core/domain/domain.core.yml
- core/domain/domain.en.yml
- core/domain/domain.fr.yml
- integration-tests-en/interactions/bot/checkin_return/ask_when_first_symptoms.jinja
- integration-tests-en/interactions/bot/checkin_return/ask_when_first_symptoms_error.jinja
- integration-tests-en/interactions/bot/daily_ci/ask_feel.jinja
- integration-tests-en/interactions/bot/daily_ci/ask_feel_error.jinja
- integration-tests-en/interactions/bot/tested_positive/ask_when_tested.jinja
- integration-tests-en/interactions/bot/tested_positive/ask_when_tested_error.jinja
- integration-tests-en/scenarios/checkin_return/no_symptoms_less.yml
- integration-tests-en/scenarios/checkin_return/no_symptoms_more_with_error.yml
- integration-tests-en/scenarios/daily_ci/feel_better_mild_symptoms_with_error.yml
- integration-tests-en/scenarios/daily_ci/feel_no_change_moderate_symptoms_with_error.yml
- integration-tests-en/scenarios/daily_ci/feel_worse_moderate_symptoms_with_error.yml
- integration-tests-en/scenarios/tested_positive/no_symptoms_less_with_error.yml
- integration-tests-en/scenarios/tested_positive/no_symptoms_more.yml
Used the `unsupported intent` policy for remaining questions. As instructed, changed the intents in more/less than 14 days questions for affirm/deny. 
Added some examples of fallback in stories, and different examples (to avoid memoization policy) in integration tests. 
does part of #350
> feat(flow): add nlu to remaining questions

- app.yml
This will fix CORS issue in dev with socket.io. This will allow the ingress to accept those new hosts and create the appropriate certificate. The hosts themselves will not be created in route 53 for now as our kubernetes clusters only support dialoguecorp.com domain
DIA-30691
> chore: create additional hosts in dev
